name: RDP Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download latest ngrok (v3)
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath $env:RUNNER_TEMP\ngrok
          Copy-Item $env:RUNNER_TEMP\ngrok\ngrok.exe -Destination $env:RUNNER_TEMP\ngrok.exe

      - name: Connect ngrok with Authtoken
        run: |
          & $env:RUNNER_TEMP\ngrok.exe config add-authtoken "2gfnRM1BCVWfE3azlJufRg7vGCs_LR8dRZo7hLWj1czG5LAR"

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok Tunnel
        run: |
          Start-Process -NoNewWindow -FilePath $env:RUNNER_TEMP\ngrok.exe -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 25
          Invoke-WebRequest -Uri http://127.0.0.1:4040/api/tunnels | Select-Object -Expand Content
