name: Start RDP Tunnel with ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: self-hosted   # must be your own Windows machine runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ngrok if missing
        shell: powershell
        run: |
          $installDir = "C:\ngrok"
          $ngrokExe = Join-Path $installDir "ngrok.exe"
          if (-not (Test-Path $ngrokExe)) {
            Write-Host "Downloading ngrok..."
            Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
            Expand-Archive ngrok.zip -DestinationPath $installDir -Force
            Remove-Item ngrok.zip
          }
          Write-Host "ngrok ready at $ngrokExe"

      - name: Enable Remote Desktop
        shell: powershell
        run: |
          # Enable RDP in registry
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0 -Force
          # Enable firewall rules
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok TCP tunnel
        shell: powershell
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          $installDir = "C:\ngrok"
          $ngrokExe = Join-Path $installDir "ngrok.exe"

          # Register token
          & $ngrokExe authtoken $env:NGROK_AUTH_TOKEN

          # Kill old ngrok if running
          Get-Process ngrok -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

          # Start ngrok TCP 3389 and capture output
          Start-Process -FilePath $ngrokExe -ArgumentList "tcp 3389" -NoNewWindow -RedirectStandardOutput "C:\ngrok\ngrok.log"

          Start-Sleep -Seconds 5

          # Show endpoint in logs
          $content = Get-Content "C:\ngrok\ngrok.log" -Tail 50
          $endpoint = ($content | Select-String -Pattern "tcp://").ToString()
          Write-Host "===================================="
          Write-Host " Public RDP endpoint via ngrok:"
          Write-Host " $endpoint"
          Write-Host "===================================="
